### ISSUE TITLE
Auto Load Game Mod not updated for current smapi version

### ISSUE THREAD

**Issue by yatsukiko** [norimicry/stardew-multiplayer-docker#1]
Like title, the mod hasn't been updated in long time and it doesn't load for me. I don't see any docs on what to do about it but it seems odd that this mod is in this repo and hasn't been mentioned or just removed. 

However, I've decompiled the mod and recompiled it with new smapi, tested it and it works fine. 
Here is the compiled mod: https://i.yatsukiko.me/XoCI8/xInOyoJI60.zip

Here is source code if you prefer compile it yourself: https://i.yatsukiko.me/XoCI8/zObavEFi98.zip

**Comment by cavazos-apps** [comment]
I thought I updated all the mods when putting this together and made sure they worked but perhaps I missed this one. I'll take a look and get it updated.

**Comment by yatsukiko** [comment]
My bad, I misread, maybe I'm a bit tired but seems like Remote Control is outdated while AutoLoadGame is not properly loaded in, 

> [23:25:48 INFO  SMAPI] Found 4 mods with warnings:
[23:25:48 ERROR SMAPI]    Skipped mods
[23:25:48 ERROR SMAPI]    --------------------------------------------------
[23:25:48 ERROR SMAPI]       These mods could not be added to your game.
[23:25:48 ERROR SMAPI]       - AutoLoadGame because it contains files, but none of them are manifest.json.
[23:25:48 ERROR SMAPI]       - Remote Control 1.0.0 because it's no longer compatible. Please check for a new version at https://smapi.io/mods



From what i see a new directory "mods" is created (in root of stardew-multiplayer-docker folder) where only AutoLoadGame is in it but it only contains config.json, when i run a bash inside container i can see that it is only config.json is in the mod folder.

Am I missing something?

I might be a bit tired to understand it, sorry for spam-ish issue.

**Comment by cavazos-apps** [comment]
It seems Remote Control hasn't been updated in 4 years and the dev doesn't appear to be active on GH anymore, so I will likely just remove that (I remember having issues updating that now). If you've already done the work to get Auto Load Game working with 1.6 then I can add that to this version. 

My initial priority was getting a working 1.6 server up for everyone and didn't have the time to do extensive testing so thank you for finding this. 😄

**Comment by cavazos-apps** [comment]
Tested and should now automatically update correct files to auto load your game. Also found a null value that should have been true. Thank you for supplying the updated mod.
