### ISSUE TITLE
[REQUEST]: A way to generate invite codes as non-host

### ISSUE THREAD

**Issue by Epipeppy** [norimicry/stardew-multiplayer-docker#10]
I was able to get the server up and running, and I can join it locally, but I'm not sure how to invite friends to the game.  It looks like the Remote Control Mod used to allow you to do this, but it's been removed; though it is still mentioned in readme under the mods used section.  Alternatively, is there a way to link the game in docker to my steam account, so I can generate said invite codes?

**Comment by cavazos-apps** [comment]
```Invite Code: Invite Code connections are routed through Steam/GoG . I've provided two methods for delivering your game's current invite code to players: Invite Code Auto Copy/Paste: The server will copy the most up-to-date invite code to the clipboard (on by default in the config.json file) whenever it changes. You can then use a macro program of your choice to paste that code into the chat service of your choice so that your non-steam friends can always have access to the most up-to-date invite code even when you are not there. For your convenience I've included an AutoHotkey script under the Files Tab> Optional Files﻿ here on Nexus that you can use. Run the Game Server>Run the AutoHotKey﻿ Script>Open Discord or other chat service and click into the chatbox of that service. The current invite code for your game will be pasted and sent every two minutes. Do not close the chat window of your chat service or click out of the chat box or it will not work. When the game server is turned off it will no longer copy the key so be sure to turn off AutoHotKey as well. Invite Code Bot: ﻿The server will copy the invite code to an "InviteCode.txt" file in the same folder as the mod. You can use this to make a bot for a chat service/website/etc. I've provided the code for a node.js Discord bot in the "Discord Bots" section at the bottom of this page.```

See [Always On Server](https://www.nexusmods.com/stardewvalley/mods/2677?tab=description) for more info.

**Comment by Epipeppy** [comment]
You are copying and pasting outdated information, and ignoring my post.  The first **sentence** of your copied text even says you need to use your Steam/GoG account, which is why I asked: "Alternatively, is there a way to link the game in docker to my steam account, so I can generate said invite codes?"

**Comment by cavazos-apps** [comment]
I'm not the maintainer for that mod and someone else submitted the code to make it compatible for 1.6. The mod appears to be designed for using on your own instance of the game, thus the description of joining from Steam/GoG, so my apologies - I misinterpreted the question. As a workaround, I recommend port forwarding (the method I use) to the machine hosting the container and using your external IP as a direct connection.

**Comment by Epipeppy** [comment]
Apologies from me as well, I should have been kinder' clearly I wasn't in a great mood yesterday.  Thank you for the suggestion!
