### ISSUE TITLE
[REQUEST]: Update for 1.6.4

### ISSUE THREAD

**Issue by pinduzera** [norimicry/stardew-multiplayer-docker#11]
Probably the fix is just to upload a newer version to cloudfare, but afaik, GOG doesn´t have the 1.6.4 yet. Maybe in a couple days?

**Comment by cavazos-apps** [comment]
I have to manually update the files so I will close this once they're updated. I don't play regularly so I'm not always aware when the game is updated. Thank you for the heads up.

**Comment by cavazos-apps** [comment]
Game files have been updated to 1.6.5.
