### ISSUE TITLE
1.6.5 version update

### ISSUE THREAD

**Issue by hyundp** [norimicry/stardew-multiplayer-docker#13]
I did git pull and docker-compose build --no-cache, but still version 1.6.3.
I think gog's stardew valley lastest version is 1.6.3.

**Comment by pinduzera** [comment]
Probably. I've tried locally just replacing the game files by the steam ones but didn't work. 
Maybe if I knew the specific one could do kind of hack, but no idea right now.

**Comment by cavazos-apps** [comment]
This should be resolved now, updated again today. Rebuild and try again.

**Comment by cavazos-apps** [comment]
![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/46500116/bba055c1-a6f2-46e5-90ef-a3d6cca31aea)
