### ISSUE TITLE
[BUG]: Version Missmatch

### ISSUE THREAD

**Issue by kennywasafk** [norimicry/stardew-multiplayer-docker#15]
I'm running into the Version Mismatch issue when connecting to the server. I've tried with a few different versions. Will list below for reference.

As the downloaded version states 1.6.5 (24110), I tried this build first, which I assumed is the latest at the moment.
- v1.6.5.24110.6670590629 (72760)

I've also tried these, to no avail.
- v1.6.4.24110.6665929918 (72751)
- v1.6.0.24079.6430277568 (72018)
- v1.5

All produce the same error when trying to connect. There seems to be no reference to the connection attempt in the container logs.

**Comment by cavazos-apps** [comment]
It is **required** to use the same version of the game as the server. Server files are currently v1.6.5 build 24110.

![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/46500116/a6f62ae4-e934-4927-8a8f-b1ced20eb518)

Ensure your game is the same version and vice versa. If you set up the server prior to me updating the files, as per the README, updating to most recent version requires a rebuild: ```git pull``` and ```docker-compose build --no-cache```. **Your save will be safe.**

**Comment by kennywasafk** [comment]
As posted above I did use to v1.6.5.24110, which seems to be the same as the in-game version (and the screenshot you posted above). I'll try to rebuild with no cache and revert. Cheers.

**Comment by cavazos-apps** [comment]
Try the rebuild and let me know. If not, screenshot the in-game version number using the VNC viewer.

**Comment by kennywasafk** [comment]
User error after all. After the rebuild everything works. Got lost between 4 different versions of the game. Thanks for getting back to me so quickly anyway!

**Comment by cavazos-apps** [comment]
Welcome! I don't play regularly so I typically appreciate these update requests since I don't always catch the updates.
