### ISSUE TITLE
[BUG]: Stardew doesn't start, complain about Stardew version

### ISSUE THREAD

**Issue by pinduzera** [norimicry/stardew-multiplayer-docker#16]
There is something really fishy going with the Stardew version and building. After updating, the mod updated but the game didn't.

![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/14168996/e89484ed-4ef8-4d49-92f7-fc33b7beedb0)

**Comment by norimicry** [comment]
It says in the error. You're running 1.6.3. The server files were recently been updated to 1.6.5. Try updating your game.

**Comment by cavazos-apps** [comment]
Try ```git pull``` and ```docker compose build --no-cache```. Seems like your container hasn't updated to 1.6.5.

**Comment by pinduzera** [comment]
Did that 3 times already, on different computers. For some reason still builds with a not updated version.
I've actually downloaded your cloudcraft link manually and it still points to a 1.6.3 version for whatever reason. Maybe some weird cache? 

Just downloaded again directly:
![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/14168996/ee62ba7c-4427-49f9-ad99-d97b500469b5)

**Comment by cavazos-apps** [comment]
Odd, yours says March 28th but the files on the file host say April 21st. Inside gameinfo, line 2 should say the build, files on the server currently say 1.6.5.24110.6670590629. 

![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/46500116/c59213d1-a899-4a32-b6ae-8d064b929d89)

Edit: Weird, I did the wget command directly and got the same file you did. Very weird. I'll look into it.

**Comment by pinduzera** [comment]
Ok, something extremely bizarre is happening between my network and the cloudcraft server.

I've used the same link using a TOR Browser through the TOR network and it downloaded the updated file. Will build the container using that locally.

I really appreciate the help, closing the ticket.

**Comment by cavazos-apps** [comment]
Just weird that I am able to reproduce this. I work with someone else to host the files (may change due to issues like this), I'll look into if there is any sort of file caching because that's definitely weird. Thanks for pointing that out and glad its working!
