### ISSUE TITLE
Please Update

### ISSUE THREAD

**Issue by xshortbusx** [norimicry/stardew-multiplayer-docker#18]
**Failure to answer these questions may result in your issue being dismissed as proper assistance may not be able to be provided.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add logs provided by the application [formatted accordingly](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

**Desktop (please complete the following information):**

**Additional context**

**Comment by dlach524** [comment]
An update just rolled out today pushing the game up to version 1.6.6 build 24117. As such, the container will need to have the Stardew version updated when time permits. Version mismatch since Steam updated our games automatically :(

**Comment by cavazos-apps** [comment]
![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/46500116/c9ebb5f7-ec8b-422e-a429-bb4997ca0a22)

Updated to 1.6.6 build 24117

**Comment by xshortbusx** [comment]
i do a git pull and it says "up to date" Still get a mismatch.

**Comment by cavazos-apps** [comment]
ConcernedApe's team has let me know distributing game files in the manner the original code base had is against the license terms (and illegal) so unfortunately I will not be able to update it anymore to respect CA's work. Users will have to use their own game files going forward. I will have to rewrite some instructions on how to do this as I understand not everyone is familiar with docker but it will take some time.
