### ISSUE TITLE
[BUG]: Please create a new script for the update dated April 28.

### ISSUE THREAD

**Issue by bulkkori** [norimicry/stardew-multiplayer-docker#23]
![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/116586949/7fac30cd-93fe-4bbc-8427-1e3ba9e3f668)

There seems to be a problem with the script not working as shown in the image above.

Please create a new script for the update dated April 28.

**Comment by cavazos-apps** [comment]
Please view the update in the README on the main page. ConcernedApe has asked I stop sharing game files and I will no longer be updating them. You will need to use your own game files. I will be updating the instructions on how to use your own, I just haven't gotten around to it yet. I will try to within the next couple days.

**Comment by cavazos-apps** [comment]
If you own the game through Steam, preliminary instructions have been added.
