### ISSUE TITLE
[BUG]: Remote connection ceases to function

### ISSUE THREAD

**Issue by dlach524** [norimicry/stardew-multiplayer-docker#24]
Does anyone else have the remote connection eventually cease to function while the container is running and the server can still be joined by players?

I'm using the Steam file version on Windows 11.
```
docker compose -f docker-compose-steam.yml up 
```
I can remotely connect to it initially and use it for a while, but when I walk away from my PC and come back later, VNC is stuck and it's not possible to reconnect with it nor through web browser. The server is still responsive and people can still join and play, but it's no longer possible to remote control the server player. If I try via web browser, it just loads and loads and doesn't get anywhere.

To resolve this, I need to stop the container and start it back up again.

Here's what the log shows, if anything:

```
stardew  | 02/05/2024 16:21:09 Got connection from client 172.20.0.1
stardew  | 02/05/2024 16:21:09   other clients:
stardew  | 02/05/2024 16:21:09 Normal socket connection
stardew  | 02/05/2024 16:21:09 Disabled X server key autorepeat.
stardew  | 02/05/2024 16:21:09   to force back on run: 'xset r on' (3 times)
stardew  | 02/05/2024 16:21:09 incr accepted_client=1 for 172.20.0.1:34966  sock=11
stardew  | 02/05/2024 16:21:09 Client Protocol Version 3.8
stardew  | 02/05/2024 16:21:09 Protocol version sent 3.8, using 3.8
stardew  | 02/05/2024 16:21:09 rfbProcessClientSecurityType: executing handler for type 2
stardew  | 02/05/2024 16:21:10 created   xdamage object: 0x40002a
stardew  | 02/05/2024 16:21:10 copy_tiles: allocating first_line at size 39
stardew  | 02/05/2024 16:21:14 client_set_net: 172.20.0.1  1.0522
stardew  | 02/05/2024 16:21:14 Using image quality level 6 for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Using JPEG subsampling 0, Q79 for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Enabling NewFBSize protocol extension for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Enabling LastRect protocol extension for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Enabling cursor position updates for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Enabling full-color cursor updates for client 172.20.0.1
stardew  | 02/05/2024 16:21:14 Using tight encoding for client 172.20.0.1
stardew  | 02/05/2024 16:21:18 created selwin: 0x40002b
stardew  | 02/05/2024 16:21:18 called initialize_xfixes()
stardew  | 02/05/2024 16:26:16 idle keyboard:   turning X autorepeat back on.
stardew  | 02/05/2024 16:33:37 collect_xdamage: too many xdamage events 1000+76691
stardew  | 02/05/2024 16:34:41 client 1 network rate 7102.4 KB/sec (370501.3 eff KB/sec)
stardew  | 02/05/2024 16:34:41 client 1 latency:  0.5 ms
stardew  | 02/05/2024 16:34:41 dt1: 0.0036, dt2: 0.0083 dt3: 0.0005 bytes: 82825
stardew  | 02/05/2024 16:34:41 link_rate: LR_LAN - 1 ms, 7102 KB/s
stardew  | 02/05/2024 16:40:56 active keyboard: turning X autorepeat off.
stardew  | 02/05/2024 16:41:03 event leak: 78636 queued,  calling XSync(dpy, True)
stardew  | 02/05/2024 16:41:03   for diagnostics run: 'x11vnc -R debug_xevents:1'
stardew  | 02/05/2024 16:46:00 idle keyboard:   turning X autorepeat back on.
stardew  | 02/05/2024 17:21:05 event leak: 41541 queued,  calling XSync(dpy, True)
stardew  | 02/05/2024 17:21:05   for diagnostics run: 'x11vnc -R debug_xevents:1'
stardew  | 02/05/2024 17:34:03 collect_xdamage: too many xdamage events 1000+81982
```
And nothing else appears for subsequent connection attempts by VNC or web browser. Not sure if it's just me, a byproduct of the new Steam game file mode, or something else.

**Comment by cavazos-apps** [comment]
Unfortunately I don't own it for Steam so I won't be able to troubleshoot this but I'll see if the contributor that added that portion can take a look.

**Comment by pinduzera** [comment]
I am taking a look, I was able to reproduce the error already but will take a while to figure out what is actually going on.

There is no reason to happen here and not on GOG one so, let me dig a little :)

**Comment by norimicry** [comment]
Wonderful, thank you!On May 3, 2024, at 8:32 AM, Eduardo Ochetski Hellas ***@***.***> wrote:﻿
I am taking a look, I was able to reproduce the error already but will take a while to figure out what is actually going on.
There is no reason to happen here and not on GOG one so, let me dig a little :)

**Comment by pinduzera** [comment]
No need to rebuild the container, just update the compose file with the new environment variable and restart the container fixes the issue. 

Open the PR if you are curious about what was going on.
