### ISSUE TITLE
[REQUEST]:pass this to a Pterodactyl egg

### ISSUE THREAD

**Issue by diaverso** [norimicry/stardew-multiplayer-docker#3]
**Describe the solution you'd like**
pass this to a Pterodactyl egg, to make it easier to run.
Here is the website of the system: https://pterodactyl.io/
the egg github: https://github.com/parkervcp/eggs
how to create a custom egg: https://pterodactyl.io/community/config/eggs/creating_a_custom_egg.html

**Comment by cavazos-apps** [comment]
Something like this is very low on my list but if I get to it, I'll work it but is not currently a priority. Will leave this open for the time-being.
