### ISSUE TITLE
[REQUEST]:someone else's save intrusion problem

### ISSUE THREAD

**Issue by xczsonn** [norimicry/stardew-multiplayer-docker#30]
When connected directly through LAN, it is easy to break into other people's saves because it does not go through steam authentication. Is there any way to host the game exclusively for invitation code to prevent this?

**Comment by cavazos-apps** [comment]
Please elaborate how it would be "easy to break into other people's saves." The save is located on your machine in the ```valley_saves/``` directory.

**Comment by xczsonn** [comment]
It doesn't mean access to the server's save 'file'. Server members can choose which farmer's information to access when accessing the LAN server. it can easily steal other people's items. This is not possible when you connect to the server through 'invite code'.
![image](https://github.com/norimicry/stardew-multiplayer-docker/assets/12751277/fe6a697e-acbc-4ad4-a224-80011ba73e4a)

**Comment by xczsonn** [comment]
Or it would be nice to have a auth mod..

**Comment by pinduzera** [comment]
It is a very chill game to play with each other and share stuff. If someone is stealing your items you should change friends.
Or develop a mod for such.

With that said, probably it is a mod issue, and not meant for here.

**Comment by norimicry** [comment]
I can't speak for Steam but even through the GoG authentication servers, people can select other characters. This may just be how the co-op is for Stardew. It isn't meant to be a widely multiplayer game but we have modded it to be such. As @pinduzera said, if you have people on your server that aren't to be trusted with other characters, that is a friend problem and shouldn't be on the server anyway.

**Comment by cavazos-apps** [comment]
The container does not run through the GoG or Steam authentication layers. Doing so would require running the host through your own Steam or GoG account (and the additional complexities that accompany that), and would not allow you to join. To achieve this you would just run these same mods on your typical game installation, but with how the container requires a host "player" this would not be feasible. As @pinduzera said, if you have people on your server that aren't to be trusted with other characters, that is a friend problem and shouldn't be on the server anyway. As such, feel free to explore additional modding options for your own instance but that is outside the scope of this project.
