### ISSUE TITLE
[REQUEST]: Add support custom mods

### ISSUE THREAD

**Issue by TIplur-ka** [norimicry/stardew-multiplayer-docker#32]
Overall, I am very happy with this server, thank you very much. But I would like to understand in more detail how you can install your own mods? I just wanted to add support for Stardew Valley Expanded, but in the end I couldn't do anything, although I tried to add it following the example of other already pre-installed mods.

Is it possible to get a modding version or a more detailed guide on how to install any mods available for 1.6?

**Comment by cavazos-apps** [comment]
You should just be able to add it to the ```docker/mods``` folder and it will get added to the container and SMAPI will pick it up.

[Expanded Install Guide](https://github.com/FlashShifter/StardewValleyExpanded/wiki/Install-guide) should provide the correct info. Make sure you have the required mods. The mod folder in this case would just be ```docker/mods```.

**Comment by TIplur-ka** [comment]
> You should just be able to add it to the `docker/mods` folder and it will get added to the container and SMAPI will pick it up.

I tried, in general it just ignores most of the modifications, I also looked inside the container and did not see the mods I added there after installing them in the mods folder. 

> [Expanded Install Guide](https://github.com/FlashShifter/StardewValleyExpanded/wiki/Install-guide) should provide the correct info. Make sure you have the required mods. The mod folder in this case would just be `docker/mods`.

Well, I will try to study this case in more detail, in which case I will write down the full situation!

**Comment by cavazos-apps** [comment]
If not, add ```- ENABLE_<modfoldername>_MOD=${ENABLE_<modfoldername>_MOD-true}``` for each mod in the ```docker-compose-<platform>.yml```. Ensure it is exactly as the folder name for correct parsing. I,e, if the folder name is StardewValleyExpanded the environmental variable would be ```- ENABLE_STARDEWVALLEYEXPANDED_MOD=${ENABLE_STARDEWVALLEYEXPANDED_MOD-true}```.

So in this case it would be:

```
#StardewValleyExpanded
- ENABLE_STARDEWVALLEYEXPANDED_MOD=${ENABLE_STARDEWVALLEYEXPANDED_MOD-true}
#ContentPatcher
- ENABLE_CONTENTPATCHER_MOD=${ENABLE_CONTENTPATCHER_MOD-true}
#FarmTypePatcher
- ENABLE_FARMTYPEPATCHER_MOD=${ENABLE_FARMTYPEPATCHER_MOD-true}
```

**Comment by TIplur-ka** [comment]
> You should just be able to add it to the `docker/mods` folder and it will get added to the container and SMAPI will pick it up.

I understand that saving maps can also be pulled from `valley_saves`?

**Comment by cavazos-apps** [comment]
> I understand that saving maps can also be pulled from `valley_saves`?

Preexisting saves, yes. Like if you wanted to transfer a save, it would go in that directory.

**Comment by TIplur-ka** [comment]
> If not, add `- ENABLE_<modfoldername>_MOD=${ENABLE_<modfoldername>_MOD-true}` for each mod in the `docker-compose-<platform>.yml`. Ensure it is exactly as the folder name for correct parsing. I,e, if the folder name is StardewValleyExpanded the environmental variable would be `- ENABLE_STARDEWVALLEYEXPANDED_MOD=${ENABLE_STARDEWVALLEYEXPANDED_MOD-true}`.

Oooooookay, it worked. But it's still better to implement something like a Wiki.  I understand that this is just a continuation and maintenance for the new version, but it would be more appropriate for you to make guides. In general, it worked, although earlier I tried to do everything according to the same example and it didn't work, maybe I was doing something wrong. I would also like to clarify that there may be errors in mods that use sounds and music, but I don't think this is critical.

Thanks!

**Comment by cavazos-apps** [comment]
Sounds only don't work via the _VNC_ if I'm not mistaken. They should work fine via the game client. But I'll update the readme for custom mods at some point. Glad it worked.
