### ISSUE TITLE
[BUG]: having problem trying to unzip the stardewvalley.sh files

### ISSUE THREAD

**Issue by faryzowskie** [norimicry/stardew-multiplayer-docker#41]
hi,im sorry but i have tried to unzip the.sh file. i have spent like 4 hours now.please i got an error when i tryna execute the .sh file.

![IMG_20240812_033912_385](https://github.com/user-attachments/assets/1f35b100-3f0f-40b0-ba56-2ddaafe7a7f4)

**Comment by cavazos-apps** [comment]
What .sh file are you executing? You shouldn't be executing any .sh file. To unzip the .sh, use `unzip <file_name.sh>`. 

> To use game files from GOG, you will need to download the Linux installer. Sign in, go to Games, find Stardew, change the system to Linux, and download the game installer. The file will look something like stardew_valley_x.x.x.xxx.sh. **Unzip this file (using Git Bash if you are on Windows), and copy the files within the data/noarch/ directory to docker/game_data/. Start the container using docker compose -f docker-compose-gog.yml up**. To rebuild the container after updating the files, use docker compose -f docker-compose-gog.yml build --no-cache.

**Comment by faryzowskie** [comment]
> What .sh file are you executing? You shouldn't be executing any .sh file. To unzip the .sh, use `unzip <file_name.sh>`.
> 
> > To use game files from GOG, you will need to download the Linux installer. Sign in, go to Games, find Stardew, change the system to Linux, and download the game installer. The file will look something like stardew_valley_x.x.x.xxx.sh. **Unzip this file (using Git Bash if you are on Windows), and copy the files within the data/noarch/ directory to docker/game_data/. Start the container using docker compose -f docker-compose-gog.yml up**. To rebuild the container after updating the files, use docker compose -f docker-compose-gog.yml build --no-cache.

my badd🥲 
thank you so muchhh!
