### ISSUE TITLE
[BUG]: why it build so slow?

### ISSUE THREAD

**Issue by faryzowskie** [norimicry/stardew-multiplayer-docker#42]
hi sorry,i need help. after i did the docker compose docker-compose-gog.yml then it start building but it was extremely slow. what am i doing wrong here? thank you
![Uploading IMG_20240812_213132_814.jpg…]()

**Comment by cavazos-apps** [comment]
Your image does not load. It does take time to set up the container, VNC, and debian distribution to run everything. Let it complete, it won't have to do that every time. It has to download several dependencies - this is likely a limitation of your bandwidth.

**Comment by faryzowskie** [comment]
> Your image does not load. It does take time to set up the container, VNC, and debian distribution to run everything. Let it complete, it won't have to do that every time. It has to download several dependencies - this is likely a limitation of your bandwidth.

hi bro, thank you .finally i could run it.may i ask,, can i join the multiplayer server from stardew valley  android?

**Comment by cavazos-apps** [comment]
Stardew Valley does not support cross play.
