### ISSUE TITLE
[BUG]: /etc/locale.gen is missing

### ISSUE THREAD

**Issue by jpotter23** [norimicry/stardew-multiplayer-docker#45]
Ran into an issue where DockerFile-steam line 29:

Would fail due to `/etc/locale.gen` is missing.

The fix was updated line 15 to install the `locales` package as well.

**Comment by jpotter23** [comment]
I suspect the same holds true for DockerFile-gog as well

**Comment by cavazos-apps** [comment]
Issue caused by #44. Thanks for letting me know. Should only be a problem with Steam but added ```locales``` to the GoG version as well.
