### ISSUE TITLE
[QUESTION]: Can Windows Store or Console versions of the game connect to this?

### ISSUE THREAD

**Issue by TreeBranches** [norimicry/stardew-multiplayer-docker#51]
It's not mentioned anywhere, but I was interested in setting up a dedicated server for me and my friend to connect to.

However I only want to do this if I can connect either via the Windows Store or the Xbox version of the game as they're the copies me and my friend own.

If not, is it something that will be implemented?

Additionally, can achievements still be earned for players connecting to this dedicated server?

I understand that I'll need a GOG or Steam version of the game for the required files during server installation - that's fine and not what I'm asking for.

**Comment by cavazos-apps** [comment]
Stardew is **not** cross play compatible between PC and console. I believe this would allow the Microsoft Store version to connect but not Xbox. And I'm fairly certain achievements can still be earned.
